version: '3.9'

services:
  slackgptbot:
    container_name: "chatgpt-slackbot${NAME_SUFFIX:-dev}"
    build: .
    working_dir: /root/
    volumes:
      - ./opt:/root/opt
    env_file:
      - ./opt/.env
    tty: true
    restart: unless-stopped
