display_information:
  name: chatgpt-slackbot
features:
  bot_user:
    display_name: chatgpt-slackbot
    always_online: false
settings:
  event_subscriptions:
    bot_events:
      - message.channels
      - message.groups
      - message.im
      - message.mpim
  interactivity:
    is_enabled: true
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false